### ISSUE TITLE
[2021-11-16] todo + issue

### ISSUE THREAD

**Issue by minzihun** [minzihun/climate-perception-analysis#2]
**2021-11-16**
- [ ] twint 스크래핑 에러 해결
- [ ] 스크래핑 코드 작성
- [ ] 스크래핑 결과 파일 hdfs에 올라가는 것 확인

> :bug: or :memo:
>
>
>
>
>
